services:
  open-webui:
    environment:
      - WHISPER_MODEL=medium
      - AUDIO_TTS_ENGINE=openai
      - AUDIO_TTS_OPENAI_API_BASE_URL=http://openai-edge-tts:5050
      - AUDIO_TTS_OPENAI_API_KEY=your_api_key_here
      - AUDIO_TTS_VOICE=ru-RU-DmitryNeural
