services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=$OPENAI_API_BASE_URL
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - ENABLE_OLLAMA_API=False
      - "WEBUI_SECRET_KEY="
      - AUDIO_TTS_ENGINE=openai
      - AUDIO_TTS_OPENAI_API_BASE_URL=http://openai-edge-tts:5050
      - AUDIO_TTS_OPENAI_API_KEY=your_api_key_here
      - AUDIO_TTS_VOICE=ru-RU-DmitryNeural
    networks:
      - open-webui-network
      - open-webui-workspace-network

volumes:
  open-webui:
    name: open-webui

networks:
  open-webui-network:
    name: open-webui-network
  open-webui-workspace-network:
    external: true
