[paths]
environments_path = "./environments"
extensions_dirs = [
    "extensions/database",
    "extensions/tts",
    "extensions/providers",
    "extensions",
]

[build]
extensions = [
    "oidc",
    "postgresql",
    "sqlite",
    "ollama",
    "openai",
    "openai-edge-tts",
    "openedai-speech",
    "step-ca-trust",
]

[build.combos]
"openai+oidc" = ["openai", "oidc"]
"openai+oidc-trust" = ["openai", "oidc", "step-ca-trust"]
"oidc-trust" = ["oidc", "step-ca-trust"]

[build.environments]
available = ["forwarding", "letsencrypt", "step-ca"]

[build.environments.forwarding]
extensions = ["openai"]

[build.environments.letsencrypt]
extensions = ["openai", "oidc", "postgresql"]
combos = ["openai+oidc"]

[build.environments.step-ca]
extensions = ["openai"]
combos = ["oidc-trust", "openai+oidc-trust"]
