services:
  open-webui:
    environment:
      ENABLE_OPENAI_API: ${ENABLE_OPENAI_API:-true}
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_API_BASE_URLS: ${OPENAI_API_BASE_URLS:-}
      OPENAI_API_KEYS: ${OPENAI_API_KEYS:-}
      TASK_MODEL_EXTERNAL: ${TASK_MODEL_EXTERNAL}