services:
  openedai-speech:
    build: .
    container_name: openedai-speech
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TTS_HOME=/app/voices
      - HF_HOME=/app/voices
      - PRELOAD_MODEL=xtts
    restart: unless-stopped
    networks:
      - open-webui-network

networks:
  open-webui-network:
    external: true
