services:
  openedai-speech:
    build: .
    container_name: openedai-speech
    environment:
      - TTS_HOME=/app/voices
      - HF_HOME=/app/voices
      - PRELOAD_MODEL=ru_RU-ruslan-medium
    restart: unless-stopped
    volumes:
      - openedai-speech-voices:/app/voices
    networks:
      - open-webui-network

volumes:
  openedai-speech-voices:
    name: openedai-speech-voices

networks:
  open-webui-network:
    external: true
